<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <NoWarn>$(NoWarn);0649</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../third_party/openvr/headers/openvr_api.cs" Link="OpenVR.cs" />
    <None Include="../../third_party/openvr/bin/win64/openvr_api.dll" Link="openvr_api.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../third_party/openvr/LICENSE" Link="OpenVR-LICENSE.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
