// Generated by tools/prepare_engineer_model_data.py from original MDLs.
// Regenerate with tools/prepare_engineer_asset_config.py; do not hand-edit.
class VREngineerModelData extends Object;

struct ModelSection
{
    var name MeshName, GroupName;
    var int Variant, Slot;
};
struct ModelEvent
{
    var name MeshName, SequenceName, GroupName, CueName;
    var int Variant;
    var float Cycle;
};
var array<ModelSection> Sections;
var array<ModelEvent> Events;

static simulated function SetBodygroup(SkeletalMeshComponent Mesh, name ModelName, name GroupName, int Variant)
{
    local int I;
    for (I = 0; I < default.Sections.Length; ++I)
        if (default.Sections[I].MeshName == ModelName && default.Sections[I].GroupName == GroupName)
            Mesh.ShowMaterialSection(default.Sections[I].Slot, default.Sections[I].Variant == Variant, 0);
}

static simulated function ResetSections(SkeletalMeshComponent Mesh, name ModelName)
{
    local int I;
    for (I = 0; I < default.Sections.Length; ++I)
        if (default.Sections[I].MeshName == ModelName)
            Mesh.ShowMaterialSection(default.Sections[I].Slot, default.Sections[I].Variant == 0, 0);
}

static simulated function Advance(Actor Context, SkeletalMeshComponent Mesh, name ModelName,
    name SequenceName, float FromCycle, float ToCycle)
{
    local int I;
    for (I = 0; I < default.Events.Length; ++I)
        if (default.Events[I].MeshName == ModelName && default.Events[I].SequenceName == SequenceName
            && default.Events[I].Cycle > FromCycle && default.Events[I].Cycle <= ToCycle)
        {
            if (default.Events[I].GroupName != '')
                SetBodygroup(Mesh, ModelName, default.Events[I].GroupName, default.Events[I].Variant);
            if (default.Events[I].CueName != '')
                class'VREngineerPresentation'.static.PlayCue(Context, default.Events[I].CueName);
        }
}

defaultproperties
{
    Sections(0)=(MeshName="SentryBlueprint",GroupName="sentry1",Variant=0,Slot=0)
    Sections(1)=(MeshName="SentryBlueprint",GroupName="sentry1",Variant=0,Slot=1)
    Sections(2)=(MeshName="SentryBlueprint",GroupName="sentry1_range",Variant=1,Slot=2)
    Sections(3)=(MeshName="SentryBlueprint",GroupName="sentry1_range",Variant=1,Slot=3)
    Sections(4)=(MeshName="SentryBlueprint",GroupName="sentry1_range_mini",Variant=1,Slot=4)
    Sections(5)=(MeshName="SentryBlueprint",GroupName="sentry1_range_mini",Variant=1,Slot=5)
    Sections(6)=(MeshName="Sentry1",GroupName="sentry",Variant=0,Slot=0)
    Sections(7)=(MeshName="Sentry1",GroupName="arms",Variant=0,Slot=1)
    Sections(8)=(MeshName="Sentry1",GroupName="mini_sentry_light",Variant=1,Slot=2)
    Sections(9)=(MeshName="Sentry2",GroupName="sentry2",Variant=0,Slot=0)
    Sections(10)=(MeshName="Sentry2",GroupName="sentry2",Variant=0,Slot=1)
    Sections(11)=(MeshName="Sentry2",GroupName="sentry2_laser",Variant=0,Slot=2)
    Sections(12)=(MeshName="Sentry3",GroupName="sentry3",Variant=0,Slot=0)
    Sections(13)=(MeshName="Sentry3",GroupName="sentry3",Variant=0,Slot=1)
    Sections(14)=(MeshName="Sentry3",GroupName="sentry3",Variant=0,Slot=2)
    Sections(15)=(MeshName="Sentry3",GroupName="Rockets",Variant=0,Slot=3)
    Sections(16)=(MeshName="Sentry3",GroupName="sentry3_laser",Variant=0,Slot=4)
    Sections(17)=(MeshName="Sentry1Build",GroupName="sentry",Variant=0,Slot=0)
    Sections(18)=(MeshName="Sentry1Build",GroupName="toolbox",Variant=0,Slot=1)
    Sections(19)=(MeshName="Sentry1Build",GroupName="arms",Variant=1,Slot=2)
    Sections(20)=(MeshName="Sentry1Build",GroupName="mini_sentry_light",Variant=1,Slot=3)
    Sections(21)=(MeshName="Sentry2Build",GroupName="sentry2",Variant=0,Slot=0)
    Sections(22)=(MeshName="Sentry2Build",GroupName="sentry2",Variant=0,Slot=1)
    Sections(23)=(MeshName="Sentry2Build",GroupName="S1Casing",Variant=0,Slot=2)
    Sections(24)=(MeshName="Sentry2Build",GroupName="S1Casing",Variant=1,Slot=3)
    Sections(25)=(MeshName="Sentry2Build",GroupName="S1muzzle",Variant=1,Slot=4)
    Sections(26)=(MeshName="Sentry2Build",GroupName="S2Guns",Variant=1,Slot=5)
    Sections(27)=(MeshName="Sentry2Build",GroupName="S2Lid",Variant=0,Slot=6)
    Sections(28)=(MeshName="Sentry2Build",GroupName="sentry2_laser",Variant=0,Slot=7)
    Sections(29)=(MeshName="Sentry3Build",GroupName="sentry3",Variant=0,Slot=0)
    Sections(30)=(MeshName="Sentry3Build",GroupName="sentry3",Variant=0,Slot=1)
    Sections(31)=(MeshName="Sentry3Build",GroupName="sentry3",Variant=0,Slot=2)
    Sections(32)=(MeshName="Sentry3Build",GroupName="boxRocket",Variant=1,Slot=3)
    Sections(33)=(MeshName="Sentry3Build",GroupName="boxRocketArm",Variant=1,Slot=4)
    Sections(34)=(MeshName="Sentry3Build",GroupName="stabilizerPads",Variant=1,Slot=5)
    Sections(35)=(MeshName="Sentry3Build",GroupName="sentry3_laser",Variant=0,Slot=6)
    Sections(36)=(MeshName="SentryShield",GroupName="repair",Variant=0,Slot=0)
    Events(0)=(MeshName="Sentry1",SequenceName="Source_idle_off",Cycle=0.0,GroupName="toolbox",Variant=1)
    Events(1)=(MeshName="Sentry1Build",SequenceName="Source_idle_off",Cycle=0.0,GroupName="toolbox",Variant=1)
    Events(2)=(MeshName="Sentry1Build",SequenceName="Source_build",Cycle=0.0,GroupName="toolbox",Variant=0)
    Events(3)=(MeshName="Sentry1Build",SequenceName="Source_build",Cycle=0.013333333656191826,CueName="sentry_upgrading1")
    Events(4)=(MeshName="Sentry1Build",SequenceName="Source_build",Cycle=0.019999999552965164,CueName="sentry_upgrading_steam1")
    Events(5)=(MeshName="Sentry1Build",SequenceName="Source_build",Cycle=0.03333333507180214,CueName="sentry_upgrading4")
    Events(6)=(MeshName="Sentry1Build",SequenceName="Source_build",Cycle=0.07666666805744171,CueName="sentry_upgrading7")
    Events(7)=(MeshName="Sentry1Build",SequenceName="Source_build",Cycle=0.10999999940395355,CueName="sentry_move_short2")
    Events(8)=(MeshName="Sentry1Build",SequenceName="Source_build",Cycle=0.1133333370089531,GroupName="arms",Variant=1)
    Events(9)=(MeshName="Sentry1Build",SequenceName="Source_build",Cycle=0.1366666704416275,CueName="sentry_upgrading_steam2")
    Events(10)=(MeshName="Sentry1Build",SequenceName="Source_build",Cycle=0.19333332777023315,CueName="sentry_upgrading2")
    Events(11)=(MeshName="Sentry1Build",SequenceName="Source_build",Cycle=0.2266666740179062,CueName="sentry_upgrading_steam3")
    Events(12)=(MeshName="Sentry1Build",SequenceName="Source_build",Cycle=0.30666667222976685,CueName="sentry_upgrading4")
    Events(13)=(MeshName="Sentry1Build",SequenceName="Source_build",Cycle=0.3866666555404663,CueName="sentry_move_medium3")
    Events(14)=(MeshName="Sentry1Build",SequenceName="Source_build",Cycle=0.4833333194255829,CueName="sentry_upgrading5")
    Events(15)=(MeshName="Sentry1Build",SequenceName="Source_build",Cycle=0.5333333611488342,CueName="sentry_upgrading_steam4")
    Events(16)=(MeshName="Sentry1Build",SequenceName="Source_build",Cycle=0.5400000214576721,CueName="sentry_move_long2")
    Events(17)=(MeshName="Sentry1Build",SequenceName="Source_build",Cycle=0.6966666579246521,CueName="sentry_upgrading7")
    Events(18)=(MeshName="Sentry1Build",SequenceName="Source_build",Cycle=0.7200000286102295,CueName="sentry_upgrading_steam5")
    Events(19)=(MeshName="Sentry1Build",SequenceName="Source_build",Cycle=0.7766666412353516,CueName="sentry_upgrading3")
    Events(20)=(MeshName="Sentry1Build",SequenceName="Source_build",Cycle=0.846666693687439,CueName="sentry_upgrading6")
    Events(21)=(MeshName="Sentry1Build",SequenceName="Source_build",Cycle=0.8666666746139526,CueName="sentry_move_short2")
    Events(22)=(MeshName="Sentry1Build",SequenceName="Source_build",Cycle=0.996666669845581,GroupName="toolbox",Variant=1)
    Events(23)=(MeshName="Sentry2Build",SequenceName="Source_upgrade",Cycle=0.0,GroupName="S1muzzle",Variant=1)
    Events(24)=(MeshName="Sentry2Build",SequenceName="Source_upgrade",Cycle=0.0416666679084301,GroupName="S1muzzle",Variant=0)
    Events(25)=(MeshName="Sentry2Build",SequenceName="Source_upgrade",Cycle=0.06666667014360428,CueName="sentry_upgrading4")
    Events(26)=(MeshName="Sentry2Build",SequenceName="Source_upgrade",Cycle=0.06666667014360428,CueName="sentry_upgrading_steam1")
    Events(27)=(MeshName="Sentry2Build",SequenceName="Source_upgrade",Cycle=0.1666666716337204,CueName="sentry_upgrading_steam4")
    Events(28)=(MeshName="Sentry2Build",SequenceName="Source_upgrade",Cycle=0.1666666716337204,CueName="sentry_upgrading8")
    Events(29)=(MeshName="Sentry2Build",SequenceName="Source_upgrade",Cycle=0.20000000298023224,GroupName="S2Lid",Variant=1)
    Events(30)=(MeshName="Sentry2Build",SequenceName="Source_upgrade",Cycle=0.2083333283662796,GroupName="S1Casing",Variant=1)
    Events(31)=(MeshName="Sentry2Build",SequenceName="Source_upgrade",Cycle=0.2083333283662796,GroupName="S2Guns",Variant=1)
    Events(32)=(MeshName="Sentry2Build",SequenceName="Source_upgrade",Cycle=0.23333333432674408,CueName="sentry_wire_connect")
    Events(33)=(MeshName="Sentry2Build",SequenceName="Source_upgrade",Cycle=0.25,CueName="sentry_move_short2")
    Events(34)=(MeshName="Sentry2Build",SequenceName="Source_upgrade",Cycle=0.4749999940395355,CueName="sentry_upgrading_steam2")
    Events(35)=(MeshName="Sentry2Build",SequenceName="Source_upgrade",Cycle=0.4749999940395355,CueName="sentry_upgrading8")
    Events(36)=(MeshName="Sentry2Build",SequenceName="Source_upgrade",Cycle=0.6499999761581421,CueName="sentry_upgrading_steam1")
    Events(37)=(MeshName="Sentry2Build",SequenceName="Source_upgrade",Cycle=0.6499999761581421,CueName="sentry_upgrading8")
    Events(38)=(MeshName="Sentry3Build",SequenceName="Source_upgrade",Cycle=0.03333333507180214,CueName="sentry_upgrading4")
    Events(39)=(MeshName="Sentry3Build",SequenceName="Source_upgrade",Cycle=0.03333333507180214,CueName="sentry_upgrading_steam1")
    Events(40)=(MeshName="Sentry3Build",SequenceName="Source_upgrade",Cycle=0.2750000059604645,GroupName="stabilizerPads",Variant=1)
    Events(41)=(MeshName="Sentry3Build",SequenceName="Source_upgrade",Cycle=0.2750000059604645,CueName="sentry_upgrading3")
    Events(42)=(MeshName="Sentry3Build",SequenceName="Source_upgrade",Cycle=0.30000001192092896,CueName="sentry_move_short2")
    Events(43)=(MeshName="Sentry3Build",SequenceName="Source_upgrade",Cycle=0.375,GroupName="boxRocket",Variant=1)
    Events(44)=(MeshName="Sentry3Build",SequenceName="Source_upgrade",Cycle=0.5,CueName="sentry_upgrading_steam4")
    Events(45)=(MeshName="Sentry3Build",SequenceName="Source_upgrade",Cycle=0.550000011920929,GroupName="boxRocketArm",Variant=1)
}
