"""Emit runtime mesh-section and sequence-event tables from original MDLs.

Generated table data stays in the staged gameplay package. It uses the exact
section ordering in the converted FBX manifest and fails on unknown events in
construction/upgrade sequences instead of dropping them.
"""
from pathlib import Path
import hashlib
import json
import re

ROOT = Path(__file__).resolve().parents[1]


def keyvalues(text):
    # Preserve duplicate keys (rndwave) and strip comments only outside quotes.
    tokens = []
    for match in re.finditer(r'//[^\r\n]*|"((?:\\.|[^"\\])*)"|([{}])|([^\s{}"]+)', text):
        if match.group().startswith('//'):
            continue
        tokens.append(match[1] if match[1] is not None else match[2] or match[3])
    at = 0
    def block(nested=False):
        nonlocal at
        result = []
        while at < len(tokens):
            key = tokens[at]; at += 1
            if key == '}':
                if not nested:
                    raise ValueError('Unmatched KeyValues closing brace')
                return result
            if at >= len(tokens) or key == '{':
                raise ValueError('Malformed KeyValues entry')
            value = tokens[at]; at += 1
            result.append((key, block(True) if value == '{' else value))
        if nested:
            raise ValueError('Unclosed KeyValues block')
        return result
    return block()


def generate(report, output):
    # Import config renderer is intentionally provided by the caller to avoid
    # executing the asset builder during this data-only conversion.
    from prepare_engineer_asset_config import ini
    sounds_file = ROOT / 'extract/engineer/scripts/game_sounds_weapons.txt'
    sounds = dict(keyvalues(sounds_file.read_text()))
    sections, events = [], []
    for mesh_name, mesh in report['models'].items():
        for slot in mesh.get('material_bodygroups', []):
            sections.append(dict(MeshName=mesh_name, GroupName=slot['group'], Variant=slot['variant'], Slot=slot['slot']))
        for sequence in mesh.get('sequences', []):
            # Running fire/aim gestures have a separate blend/event path.
            if sequence['name'] not in ('build', 'upgrade', 'idle_off'):
                continue
            for event in sorted(sequence['events'], key=lambda e: e['cycle']):
                row = dict(MeshName=mesh_name, SequenceName='Source_' + sequence['name'], Cycle=event['cycle'])
                if event['name'] == 'AE_CL_BODYGROUP_SET_VALUE':
                    group, variant = event['options'].split()
                    row.update(GroupName=group, Variant=int(variant))
                elif event['name'] in ('AE_CL_ENABLE_BODYGROUP', 'AE_CL_DISABLE_BODYGROUP'):
                    # Source events set the numeric variant, regardless of
                    # which variant happens to contain the visible model.
                    row.update(GroupName=event['options'], Variant=int(event['name'] == 'AE_CL_ENABLE_BODYGROUP'))
                elif event['event'] == 5004:
                    sound = sounds.get(event['options'])
                    if sound is None:
                        raise ValueError(f'Missing original sound definition: {event}')
                    waves = [v for k, v in sound if k.lower() == 'wave']
                    if len(waves) != 1:
                        raise ValueError(f'Animation event needs explicit random-sound mapping: {event}')
                    wave = waves[0].lstrip('*#@><^)}$!?')
                    if not (ROOT / 'extract/engineer/sound' / wave).is_file():
                        raise FileNotFoundError(wave)
                    row['CueName'] = Path(wave).stem
                else:
                    raise ValueError(f'Unhandled original model event: {mesh_name}/{sequence["name"]}: {event}')
                events.append(row)
    declarations = '''// Generated by tools/prepare_engineer_model_data.py from original MDLs.
// Regenerate with tools/prepare_engineer_asset_config.py; do not hand-edit.
class VREngineerModelData extends Object;

struct ModelSection
{
    var name MeshName, GroupName;
    var int Variant, Slot;
};
struct ModelEvent
{
    var name MeshName, SequenceName, GroupName, CueName;
    var int Variant;
    var float Cycle;
};
var array<ModelSection> Sections;
var array<ModelEvent> Events;

static simulated function SetBodygroup(SkeletalMeshComponent Mesh, name ModelName, name GroupName, int Variant)
{
    local int I;
    for (I = 0; I < default.Sections.Length; ++I)
        if (default.Sections[I].MeshName == ModelName && default.Sections[I].GroupName == GroupName)
            Mesh.ShowMaterialSection(default.Sections[I].Slot, default.Sections[I].Variant == Variant, 0);
}

static simulated function ResetSections(SkeletalMeshComponent Mesh, name ModelName)
{
    local int I;
    for (I = 0; I < default.Sections.Length; ++I)
        if (default.Sections[I].MeshName == ModelName)
            Mesh.ShowMaterialSection(default.Sections[I].Slot, default.Sections[I].Variant == 0, 0);
}

static simulated function Advance(Actor Context, SkeletalMeshComponent Mesh, name ModelName,
    name SequenceName, float FromCycle, float ToCycle)
{
    local int I;
    for (I = 0; I < default.Events.Length; ++I)
        if (default.Events[I].MeshName == ModelName && default.Events[I].SequenceName == SequenceName
            && default.Events[I].Cycle > FromCycle && default.Events[I].Cycle <= ToCycle)
        {
            if (default.Events[I].GroupName != '')
                SetBodygroup(Mesh, ModelName, default.Events[I].GroupName, default.Events[I].Variant);
            if (default.Events[I].CueName != '')
                class'VREngineerPresentation'.static.PlayCue(Context, default.Events[I].CueName);
        }
}

defaultproperties
{
'''
    declarations += '\n'.join(f'    Sections({i})={ini(s)}' for i, s in enumerate(sections)) + '\n'
    declarations += '\n'.join(f'    Events({i})={ini(e)}' for i, e in enumerate(events)) + '\n}\n'
    output.write_text(declarations)
    return dict(sections=len(sections), events=len(events), sha256=hashlib.sha256(output.read_bytes()).hexdigest(),
                source_sounds_sha256=hashlib.sha256(sounds_file.read_bytes()).hexdigest())


if __name__ == '__main__':
    report = json.loads((ROOT / 'build/engineer-meshes/manifest.json').read_text())
    print(generate(report, ROOT / 'script/EngineerStaging/Classes/VREngineerModelData.uc'))
